"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import exlcm.command_values_t

class wheel_speeds_t(object):
    __slots__ = ["timestamp", "wheel"]

    def __init__(self):
        self.timestamp = 0
        self.wheel = exlcm.command_values_t()

    def encode(self):
        buf = BytesIO()
        buf.write(wheel_speeds_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        assert self.wheel._get_packed_fingerprint() == exlcm.command_values_t._get_packed_fingerprint()
        self.wheel._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wheel_speeds_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wheel_speeds_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = wheel_speeds_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.wheel = exlcm.command_values_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if wheel_speeds_t in parents: return 0
        newparents = parents + [wheel_speeds_t]
        tmphash = (0xb4828c0f4cb62a7b+ exlcm.command_values_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if wheel_speeds_t._packed_fingerprint is None:
            wheel_speeds_t._packed_fingerprint = struct.pack(">Q", wheel_speeds_t._get_hash_recursive([]))
        return wheel_speeds_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

